server:
  port: 8989
spring:
  application:
    name: blog-message-service
eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.4:8088/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ribbon:
  http:
    client:
      enabled: true
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: false
  compression:
    request:
      min-request-size: 4096
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic