server:
  port: 8088
spring:
  application:
    name: eurake-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
    peer-node-read-timeout-ms: 12000